### ISSUE TITLE
게임 서버 todo list

### ISSUE THREAD

**Issue by hongsam14** [KMURUST/EndGame_Server#1]
- [ ] tokio docs를 활용한 socket programming
- [ ] 에러 발생시 로그를 file에 저장하고 서버가 종료되지 않게 error handling
- [ ] 서버에서 생기는 로그들을 file system을 사용하여 저장하는 것

**Comment by hongsam14** [comment]
[tokio docs](https://docs.rs/tokio/latest/tokio/)

**Comment by hongsam14** [comment]
- [ ] 클라이언트 종료 시 hash map에서 해당 키값 데이터 해제
